### PR TITLE
Preliminary Ars Nouveau Progression

### PR DESCRIPTION
**Pull request by MuteTiefling**
Have themed the crafts a bit more around the elements, with different minerals/substances representing different elements.

The idea is to put a bit of a theme behind what’s used for what.
Earth = Apatite
Water = Lapis
Fire = Sulfur
Air = Cloud Bottle
Magic = Mana Gems
Lightning = Fluorite
Life = Phyto-gro

Made the initial Charged Snowball recipe a bit more expensive to hopefully drive people towards the lightning recipe.

Arcane Stone is more generous, but with extra steps.

Lots of in game documentation added.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Hmm... Do recipe removals in Ars Nouveau not usually cause the book to glitch out? :x I recall we usually override the recipes if possible.

**Comment by MuteTiefling** [comment]
Yeah, I'll probably have to modify the book. I'll see how bad it breaks with an ID override with a different recipe type though.

Or I guess I could replace it with a dummy recipe.

**Comment by NillerMedDild** [comment]
> I'll see how bad it breaks with an ID override with a different recipe type though.

I think that'll fix it just fine :D

**Comment by NillerMedDild** [comment]
But! I think what you're doing here is really cool, I can't wait to see it in-game :D

**Comment by MuteTiefling** [comment]
Hrm, no, Adding an ID to the Interactio recipes doesn't appear to override the regular crafting table recipes. I think I've got a solution though. 

Create a new item with a custom tooltip to indicate the recipe has changed. 
Create a patchouli safe removal script that resets the crafting recipe to an uncraftable one with that item.
Hide the recipe from JEI. 

Don't know if that last step is possible though.. testing right now.

**Comment by MuteTiefling** [comment]
image

image

Now... to hide just the crafting table recipe in JEI >.>

**Comment by NillerMedDild** [comment]
Nice! I don't think hiding 1 recipe is possible, only items :/

**Comment by MuteTiefling** [comment]
oof. That does put a damper on things this way then, since it's going to leave a lot of clutter in JEI

**Comment by NillerMedDild** [comment]
Requested feature: https://github.com/KubeJS-Mods/KubeJS/issues/125 
Do you want this merged now or wait till it's completely done? I vote merge :)

**Comment by MuteTiefling** [comment]
I have a bit to add here and then I'll merge

**Pull request merged**
